<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseParameters extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('parameters');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('parameter', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '255',
             ));
        $this->hasColumn('content', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '255',
             ));
    }

}