<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseBasicExercises extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('basic_exercises');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '255',
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => false,
             'length' => '255',
             ));
        $this->hasColumn('description', 'blob', null, array(
             'type' => 'blob',
             'notnull' => true,
             ));
    }

}