<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseAthletes extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('athletes');
        $this->hasColumn('first_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => false,
             'length' => '255',
             ));
        $this->hasColumn('second_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => false,
             'length' => '255',
             ));
        $this->hasColumn('rank', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => false,
             'length' => '255',
             ));
        $this->hasColumn('biography', 'blob', null, array(
             'type' => 'blob',
             'notnull' => true,
             ));
    }

}