default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [app.css, foundation.css, main.css]

  javascripts:    [vendor/jquery.js, vendor/what-input.js, vendor/foundation.js, app.js]

  has_layout:     on
  layout:         layout
