<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2018/02/01 18:20:05

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=encyclopedia_of_weightlifting',
  'username' => 'root',
  'password' => '1234',
  'name' => 'doctrine',
)),);
