<?php
// auto-generated by sfRoutingConfigHandler
// date: 2018/02/01 18:20:05
return array(
'categories_category' => new sfDoctrineRouteCollection(array (
  'model' => 'Categories',
  'module' => 'category',
  'prefix_path' => 'category',
  'column' => 'id',
  'with_wildcard_routes' => true,
  'name' => 'categories_category',
  'requirements' => 
  array (
  ),
)),
'indexCategory' => new sfRoute('/:module/indexCategory', array (
  'module' => 'category',
  'action' => 'indexCategory',
), array (
), array (
)),
'showCategory' => new sfRoute('/:module/:id/showCategory', array (
  'module' => 'category',
  'action' => 'showCategory',
), array (
  'id' => '\\d+',
), array (
)),
'editCategory' => new sfRoute('/:module/:id/edit', array (
  'module' => 'category',
  'action' => 'editCategory',
), array (
  'id' => '\\d+',
), array (
)),
'updateCategory' => new sfRoute('/:module/:id/updateCategory', array (
  'module' => 'category',
  'action' => 'updateCategory',
), array (
), array (
)),
'updateParameters' => new sfRoute('/:module/settings/update', array (
  'module' => 'category',
  'action' => 'update',
), array (
), array (
)),
'settingsFrontedPage' => new sfRoute('/:module/settings', array (
  'module' => 'category',
  'action' => 'settings',
), array (
), array (
)),
'settingsDisplay' => new sfRoute('/:module/settingsDisplay', array (
  'module' => 'category',
  'action' => 'settingsDisplay',
), array (
), array (
)),
'homepage' => new sfRoute('/', array (
  'module' => 'category',
  'action' => 'index',
), array (
), array (
)),
'default' => new sfRoute('/:module/:action/*', array (
), array (
), array (
)),
);
