<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2018/02/01 18:20:05
return array(

  // sfProtoculousPlugin_module_libs

  // sfProtoculousPlugin_lib

  // sfDoctrinePlugin_module_libs

  // project
  'AthletesFormFilter' => 'W:/!git/service-encyclopedia/lib/filter/doctrine/AthletesFormFilter.class.php',
  'BaseAthletesFormFilter' => 'W:/!git/service-encyclopedia/lib/filter/doctrine/base/BaseAthletesFormFilter.class.php',
  'BaseBasicExercisesFormFilter' => 'W:/!git/service-encyclopedia/lib/filter/doctrine/base/BaseBasicExercisesFormFilter.class.php',
  'BaseCategoriesFormFilter' => 'W:/!git/service-encyclopedia/lib/filter/doctrine/base/BaseCategoriesFormFilter.class.php',
  'BaseFormFilterDoctrine' => 'W:/!git/service-encyclopedia/lib/filter/doctrine/BaseFormFilterDoctrine.class.php',
  'BasicExercisesFormFilter' => 'W:/!git/service-encyclopedia/lib/filter/doctrine/BasicExercisesFormFilter.class.php',
  'CategoriesFormFilter' => 'W:/!git/service-encyclopedia/lib/filter/doctrine/CategoriesFormFilter.class.php',
  'AthletesForm' => 'W:/!git/service-encyclopedia/lib/form/doctrine/AthletesForm.class.php',
  'BaseAthletesForm' => 'W:/!git/service-encyclopedia/lib/form/doctrine/base/BaseAthletesForm.class.php',
  'BaseBasicExercisesForm' => 'W:/!git/service-encyclopedia/lib/form/doctrine/base/BaseBasicExercisesForm.class.php',
  'BaseCategoriesForm' => 'W:/!git/service-encyclopedia/lib/form/doctrine/base/BaseCategoriesForm.class.php',
  'BaseParametersForm' => 'W:/!git/service-encyclopedia/lib/form/doctrine/base/BaseParametersForm.class.php',
  'BaseFormDoctrine' => 'W:/!git/service-encyclopedia/lib/form/doctrine/BaseFormDoctrine.class.php',
  'BasicExercisesForm' => 'W:/!git/service-encyclopedia/lib/form/doctrine/BasicExercisesForm.class.php',
  'CategoriesForm' => 'W:/!git/service-encyclopedia/lib/form/doctrine/CategoriesForm.class.php',
  'ParametersForm' => 'W:/!git/service-encyclopedia/lib/form/doctrine/ParametersForm.class.php',

  // project_model
  'Athletes' => 'W:/!git/service-encyclopedia/lib/model/doctrine/Athletes.class.php',
  'AthletesTable' => 'W:/!git/service-encyclopedia/lib/model/doctrine/AthletesTable.class.php',
  'BaseAthletes' => 'W:/!git/service-encyclopedia/lib/model/doctrine/base/BaseAthletes.class.php',
  'BaseBasicExercises' => 'W:/!git/service-encyclopedia/lib/model/doctrine/base/BaseBasicExercises.class.php',
  'BaseCategories' => 'W:/!git/service-encyclopedia/lib/model/doctrine/base/BaseCategories.class.php',
  'BaseParameters' => 'W:/!git/service-encyclopedia/lib/model/doctrine/base/BaseParameters.class.php',
  'BasicExercises' => 'W:/!git/service-encyclopedia/lib/model/doctrine/BasicExercises.class.php',
  'BasicExercisesTable' => 'W:/!git/service-encyclopedia/lib/model/doctrine/BasicExercisesTable.class.php',
  'Categories' => 'W:/!git/service-encyclopedia/lib/model/doctrine/Categories.class.php',
  'CategoriesTable' => 'W:/!git/service-encyclopedia/lib/model/doctrine/CategoriesTable.class.php',
  'Parameters' => 'W:/!git/service-encyclopedia/lib/model/doctrine/Parameters.class.php',
  'ParametersTable' => 'W:/!git/service-encyclopedia/lib/model/doctrine/ParametersTable.class.php',

  // application
  'myUser' => 'W:/!git/service-encyclopedia/apps/backend/lib/myUser.class.php',

  // modules
  'category/categoryGeneratorConfiguration' => 'W:/!git/service-encyclopedia/apps/backend/modules/category/lib/categoryGeneratorConfiguration.class.php',
  'category/categoryGeneratorHelper' => 'W:/!git/service-encyclopedia/apps/backend/modules/category/lib/categoryGeneratorHelper.class.php',

  // sfDoctrinePlugin_lib
  'sfDoctrineCli' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',
  'sfDoctrineConnectionListener' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfDoctrineDatabase' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'sfDoctrineDataRetriever' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDataRetriever.class.php',
  'sfWebDebugPanelDoctrine' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'sfFormDoctrine' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfFormFilterDoctrine' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'sfDoctrineColumn' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'sfDoctrineFormFilterGenerator' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfDoctrineFormGenerator' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfDoctrineGenerator' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'sfDoctrineLogger' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/log/sfDoctrineLogger.class.php',
  'sfDoctrinePager' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',
  'sfDoctrineRecord' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',
  'sfDoctrineRecordI18nFilter' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sfDoctrineRecordListener' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordListener.class.php',
  'sfDoctrineRoute' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',
  'sfDoctrineRouteCollection' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sfDoctrineException' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',
  'sfDoctrineBaseTask' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfDoctrineBuildAllLoadTask' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildAllLoadTask.class.php',
  'sfDoctrineBuildAllReloadTask' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildAllReloadTask.class.php',
  'sfDoctrineBuildAllReloadTestAllTask' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildAllReloadTestAllTask.class.php',
  'sfDoctrineBuildAllTask' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildAllTask.class.php',
  'sfDoctrineBuildDbTask' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfDoctrineBuildFiltersTask' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfDoctrineBuildFormsTask' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfDoctrineBuildModelTask' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfDoctrineBuildSchemaTask' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfDoctrineBuildSqlTask' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfDoctrineDumpDataTask' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfDoctrineLoadDataTask' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfDoctrineDqlTask' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfDoctrineDropDbTask' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfDoctrineGenerateAdminTask' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfDoctrineGenerateMigrationsDbTask' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfDoctrineGenerateMigrationsModelsTask' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfDoctrineGenerateMigrationTask' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfDoctrineGenerateModuleForRouteTask' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfDoctrineGenerateModuleTask' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfDoctrineInsertSqlTask' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfDoctrineMigrateTask' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sfDoctrineRebuildDbTask' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineRebuildDbTask.class.php',
  'sfTesterDoctrine' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',
  'sfDoctrineUniqueValidator' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfDoctrineUniqueValidator.class.php',
  'sfValidatorDoctrineChoice' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfValidatorDoctrineChoiceMany' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoiceMany.class.php',
  'sfValidatorDoctrineUnique' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'sfWidgetFormDoctrineChoice' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',
  'sfWidgetFormDoctrineChoiceMany' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoiceMany.class.php',
  'sfWidgetFormDoctrineSelect' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineSelect.class.php',
  'sfWidgetFormDoctrineSelectMany' => 'W:/!git/service-encyclopedia/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineSelectMany.class.php',
);
