<?php
// auto-generated by sfViewConfigHandler
// date: 2018/02/01 18:20:07
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (!is_null($layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout')))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (is_null($this->getDecoratorTemplate()) && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('app.css', '', array ());
  $response->addStylesheet('foundation.css', '', array ());
  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('backend_main.css', '', array ());
  $response->addJavascript('vendor/jquery.js', '', array ());
  $response->addJavascript('vendor/what-input.js', '', array ());
  $response->addJavascript('vendor/foundation.js', '', array ());
  $response->addJavascript('app.js', '', array ());


