<?php
// auto-generated by sfRoutingConfigHandler
// date: 2018/02/01 18:20:00
return array(
'indexAthletes' => new sfRoute('/athletes/indexAthletes', array (
  'module' => 'encyclopedia',
  'action' => 'indexAthletes',
), array (
), array (
)),
'indexExercises' => new sfRoute('/exercises/indexExercises', array (
  'module' => 'encyclopedia',
  'action' => 'indexExercises',
), array (
), array (
)),
'show_biography_athlete' => new sfRoute('/athletes/:id', array (
  'module' => 'encyclopedia',
  'action' => 'showAthletes',
), array (
  'id' => '\\d+',
), array (
)),
'create_record_about_athlete' => new sfRoute('/athletes/new', array (
  'module' => 'encyclopedia',
  'action' => 'newAthletes',
), array (
), array (
)),
'create_record_about_exercise' => new sfRoute('/exercises/new', array (
  'module' => 'encyclopedia',
  'action' => 'newExercises',
), array (
), array (
)),
'save_record_about_athelete' => new sfRoute('/athletes/create', array (
  'module' => 'encyclopedia',
  'action' => 'createAthletes',
), array (
), array (
)),
'save_record_about_exercise' => new sfRoute('/exercises/create', array (
  'module' => 'encyclopedia',
  'action' => 'createExercises',
), array (
), array (
)),
'show_description_exercise' => new sfRoute('/exercises/:id', array (
  'module' => 'encyclopedia',
  'action' => 'showExercises',
), array (
  'id' => '\\d+',
), array (
)),
'homepage' => new sfRoute('/', array (
  'module' => 'encyclopedia',
  'action' => 'index',
), array (
), array (
)),
'default_index' => new sfRoute('/:module', array (
  'action' => 'index',
), array (
), array (
)),
'default' => new sfRoute('/:module/:action/*', array (
), array (
), array (
)),
);
