<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/02/01 18:20:00
sfConfig::add(array(
  'app_title_of_header' => '',
  'app_pathbackgroundheader' => '../images/background_header.jpg',
  'app_pathbackgroundfooter' => '../images/background_footer.jpg',
));
